//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("NpoziomDBModel", "FK_Wiedza_Instrumenty", "Instrumenty", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BazaWiedzy.Instrumenty), "Wiedza", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BazaWiedzy.Wiedza), true)]
[assembly: EdmRelationshipAttribute("NpoziomDBModel", "FK_Wiedza_Relacje", "Relacje", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BazaWiedzy.Relacje), "Wiedza", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BazaWiedzy.Wiedza), true)]
[assembly: EdmRelationshipAttribute("NpoziomDBModel", "FK_Kategorie_Grupy", "Grupy", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BazaWiedzy.Grupy), "Kategorie", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BazaWiedzy.Kategorie), true)]
[assembly: EdmRelationshipAttribute("NpoziomDBModel", "FK_Instrumenty_Kategorie", "Kategorie", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BazaWiedzy.Kategorie), "Instrumenty", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BazaWiedzy.Instrumenty), true)]

#endregion

namespace BazaWiedzy
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class NpoziomDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new NpoziomDBEntities object using the connection string found in the 'NpoziomDBEntities' section of the application configuration file.
        /// </summary>
        public NpoziomDBEntities() : base("name=NpoziomDBEntities", "NpoziomDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NpoziomDBEntities object.
        /// </summary>
        public NpoziomDBEntities(string connectionString) : base(connectionString, "NpoziomDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NpoziomDBEntities object.
        /// </summary>
        public NpoziomDBEntities(EntityConnection connection) : base(connection, "NpoziomDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Instrumenty> Instrumenty
        {
            get
            {
                if ((_Instrumenty == null))
                {
                    _Instrumenty = base.CreateObjectSet<Instrumenty>("Instrumenty");
                }
                return _Instrumenty;
            }
        }
        private ObjectSet<Instrumenty> _Instrumenty;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Relacje> Relacje
        {
            get
            {
                if ((_Relacje == null))
                {
                    _Relacje = base.CreateObjectSet<Relacje>("Relacje");
                }
                return _Relacje;
            }
        }
        private ObjectSet<Relacje> _Relacje;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Wiedza> Wiedza
        {
            get
            {
                if ((_Wiedza == null))
                {
                    _Wiedza = base.CreateObjectSet<Wiedza>("Wiedza");
                }
                return _Wiedza;
            }
        }
        private ObjectSet<Wiedza> _Wiedza;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BazaWiedzy> BazaWiedzy
        {
            get
            {
                if ((_BazaWiedzy == null))
                {
                    _BazaWiedzy = base.CreateObjectSet<BazaWiedzy>("BazaWiedzy");
                }
                return _BazaWiedzy;
            }
        }
        private ObjectSet<BazaWiedzy> _BazaWiedzy;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Grupy> Grupy
        {
            get
            {
                if ((_Grupy == null))
                {
                    _Grupy = base.CreateObjectSet<Grupy>("Grupy");
                }
                return _Grupy;
            }
        }
        private ObjectSet<Grupy> _Grupy;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Kategorie> Kategorie
        {
            get
            {
                if ((_Kategorie == null))
                {
                    _Kategorie = base.CreateObjectSet<Kategorie>("Kategorie");
                }
                return _Kategorie;
            }
        }
        private ObjectSet<Kategorie> _Kategorie;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Instrumenty EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToInstrumenty(Instrumenty instrumenty)
        {
            base.AddObject("Instrumenty", instrumenty);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Relacje EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRelacje(Relacje relacje)
        {
            base.AddObject("Relacje", relacje);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Wiedza EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWiedza(Wiedza wiedza)
        {
            base.AddObject("Wiedza", wiedza);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BazaWiedzy EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBazaWiedzy(BazaWiedzy bazaWiedzy)
        {
            base.AddObject("BazaWiedzy", bazaWiedzy);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Grupy EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGrupy(Grupy grupy)
        {
            base.AddObject("Grupy", grupy);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Kategorie EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToKategorie(Kategorie kategorie)
        {
            base.AddObject("Kategorie", kategorie);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NpoziomDBModel", Name="BazaWiedzy")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BazaWiedzy : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BazaWiedzy object.
        /// </summary>
        /// <param name="koncept">Initial value of the Koncept property.</param>
        public static BazaWiedzy CreateBazaWiedzy(global::System.String koncept)
        {
            BazaWiedzy bazaWiedzy = new BazaWiedzy();
            bazaWiedzy.Koncept = koncept;
            return bazaWiedzy;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nazwa
        {
            get
            {
                return _Nazwa;
            }
            set
            {
                OnNazwaChanging(value);
                ReportPropertyChanging("Nazwa");
                _Nazwa = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nazwa");
                OnNazwaChanged();
            }
        }
        private global::System.String _Nazwa;
        partial void OnNazwaChanging(global::System.String value);
        partial void OnNazwaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Relacja
        {
            get
            {
                return _Relacja;
            }
            set
            {
                OnRelacjaChanging(value);
                ReportPropertyChanging("Relacja");
                _Relacja = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Relacja");
                OnRelacjaChanged();
            }
        }
        private global::System.String _Relacja;
        partial void OnRelacjaChanging(global::System.String value);
        partial void OnRelacjaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Koncept
        {
            get
            {
                return _Koncept;
            }
            set
            {
                if (_Koncept != value)
                {
                    OnKonceptChanging(value);
                    ReportPropertyChanging("Koncept");
                    _Koncept = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Koncept");
                    OnKonceptChanged();
                }
            }
        }
        private global::System.String _Koncept;
        partial void OnKonceptChanging(global::System.String value);
        partial void OnKonceptChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NpoziomDBModel", Name="Grupy")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Grupy : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Grupy object.
        /// </summary>
        /// <param name="idG">Initial value of the IdG property.</param>
        public static Grupy CreateGrupy(global::System.Int32 idG)
        {
            Grupy grupy = new Grupy();
            grupy.IdG = idG;
            return grupy;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdG
        {
            get
            {
                return _IdG;
            }
            set
            {
                if (_IdG != value)
                {
                    OnIdGChanging(value);
                    ReportPropertyChanging("IdG");
                    _IdG = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdG");
                    OnIdGChanged();
                }
            }
        }
        private global::System.Int32 _IdG;
        partial void OnIdGChanging(global::System.Int32 value);
        partial void OnIdGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nazwa
        {
            get
            {
                return _Nazwa;
            }
            set
            {
                OnNazwaChanging(value);
                ReportPropertyChanging("Nazwa");
                _Nazwa = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nazwa");
                OnNazwaChanged();
            }
        }
        private global::System.String _Nazwa;
        partial void OnNazwaChanging(global::System.String value);
        partial void OnNazwaChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NpoziomDBModel", "FK_Kategorie_Grupy", "Kategorie")]
        public EntityCollection<Kategorie> Kategorie
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Kategorie>("NpoziomDBModel.FK_Kategorie_Grupy", "Kategorie");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Kategorie>("NpoziomDBModel.FK_Kategorie_Grupy", "Kategorie", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NpoziomDBModel", Name="Instrumenty")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Instrumenty : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Instrumenty object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Instrumenty CreateInstrumenty(global::System.Int32 id)
        {
            Instrumenty instrumenty = new Instrumenty();
            instrumenty.Id = id;
            return instrumenty;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nazwa
        {
            get
            {
                return _Nazwa;
            }
            set
            {
                OnNazwaChanging(value);
                ReportPropertyChanging("Nazwa");
                _Nazwa = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nazwa");
                OnNazwaChanged();
            }
        }
        private global::System.String _Nazwa;
        partial void OnNazwaChanging(global::System.String value);
        partial void OnNazwaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> KategoriaID
        {
            get
            {
                return _KategoriaID;
            }
            set
            {
                OnKategoriaIDChanging(value);
                ReportPropertyChanging("KategoriaID");
                _KategoriaID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("KategoriaID");
                OnKategoriaIDChanged();
            }
        }
        private Nullable<global::System.Int32> _KategoriaID;
        partial void OnKategoriaIDChanging(Nullable<global::System.Int32> value);
        partial void OnKategoriaIDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NpoziomDBModel", "FK_Wiedza_Instrumenty", "Wiedza")]
        public EntityCollection<Wiedza> Wiedza
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Wiedza>("NpoziomDBModel.FK_Wiedza_Instrumenty", "Wiedza");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Wiedza>("NpoziomDBModel.FK_Wiedza_Instrumenty", "Wiedza", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NpoziomDBModel", "FK_Instrumenty_Kategorie", "Kategorie")]
        public Kategorie Kategorie
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Kategorie>("NpoziomDBModel.FK_Instrumenty_Kategorie", "Kategorie").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Kategorie>("NpoziomDBModel.FK_Instrumenty_Kategorie", "Kategorie").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Kategorie> KategorieReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Kategorie>("NpoziomDBModel.FK_Instrumenty_Kategorie", "Kategorie");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Kategorie>("NpoziomDBModel.FK_Instrumenty_Kategorie", "Kategorie", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NpoziomDBModel", Name="Kategorie")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Kategorie : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Kategorie object.
        /// </summary>
        /// <param name="idK">Initial value of the IdK property.</param>
        public static Kategorie CreateKategorie(global::System.Int32 idK)
        {
            Kategorie kategorie = new Kategorie();
            kategorie.IdK = idK;
            return kategorie;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdK
        {
            get
            {
                return _IdK;
            }
            set
            {
                if (_IdK != value)
                {
                    OnIdKChanging(value);
                    ReportPropertyChanging("IdK");
                    _IdK = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdK");
                    OnIdKChanged();
                }
            }
        }
        private global::System.Int32 _IdK;
        partial void OnIdKChanging(global::System.Int32 value);
        partial void OnIdKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nazwa
        {
            get
            {
                return _Nazwa;
            }
            set
            {
                OnNazwaChanging(value);
                ReportPropertyChanging("Nazwa");
                _Nazwa = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nazwa");
                OnNazwaChanged();
            }
        }
        private global::System.String _Nazwa;
        partial void OnNazwaChanging(global::System.String value);
        partial void OnNazwaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdG
        {
            get
            {
                return _IdG;
            }
            set
            {
                OnIdGChanging(value);
                ReportPropertyChanging("IdG");
                _IdG = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdG");
                OnIdGChanged();
            }
        }
        private Nullable<global::System.Int32> _IdG;
        partial void OnIdGChanging(Nullable<global::System.Int32> value);
        partial void OnIdGChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NpoziomDBModel", "FK_Kategorie_Grupy", "Grupy")]
        public Grupy Grupy
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Grupy>("NpoziomDBModel.FK_Kategorie_Grupy", "Grupy").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Grupy>("NpoziomDBModel.FK_Kategorie_Grupy", "Grupy").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Grupy> GrupyReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Grupy>("NpoziomDBModel.FK_Kategorie_Grupy", "Grupy");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Grupy>("NpoziomDBModel.FK_Kategorie_Grupy", "Grupy", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NpoziomDBModel", "FK_Instrumenty_Kategorie", "Instrumenty")]
        public EntityCollection<Instrumenty> Instrumenty
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Instrumenty>("NpoziomDBModel.FK_Instrumenty_Kategorie", "Instrumenty");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Instrumenty>("NpoziomDBModel.FK_Instrumenty_Kategorie", "Instrumenty", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NpoziomDBModel", Name="Relacje")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Relacje : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Relacje object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Relacje CreateRelacje(global::System.Int32 id)
        {
            Relacje relacje = new Relacje();
            relacje.Id = id;
            return relacje;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Relacja
        {
            get
            {
                return _Relacja;
            }
            set
            {
                OnRelacjaChanging(value);
                ReportPropertyChanging("Relacja");
                _Relacja = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Relacja");
                OnRelacjaChanged();
            }
        }
        private global::System.String _Relacja;
        partial void OnRelacjaChanging(global::System.String value);
        partial void OnRelacjaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Reverse
        {
            get
            {
                return _Reverse;
            }
            set
            {
                OnReverseChanging(value);
                ReportPropertyChanging("Reverse");
                _Reverse = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Reverse");
                OnReverseChanged();
            }
        }
        private global::System.String _Reverse;
        partial void OnReverseChanging(global::System.String value);
        partial void OnReverseChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NpoziomDBModel", "FK_Wiedza_Relacje", "Wiedza")]
        public EntityCollection<Wiedza> Wiedza
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Wiedza>("NpoziomDBModel.FK_Wiedza_Relacje", "Wiedza");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Wiedza>("NpoziomDBModel.FK_Wiedza_Relacje", "Wiedza", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NpoziomDBModel", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagrams object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NpoziomDBModel", Name="Wiedza")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Wiedza : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Wiedza object.
        /// </summary>
        /// <param name="idI">Initial value of the IdI property.</param>
        /// <param name="idR">Initial value of the IdR property.</param>
        /// <param name="koncept">Initial value of the Koncept property.</param>
        public static Wiedza CreateWiedza(global::System.Int32 idI, global::System.Int32 idR, global::System.String koncept)
        {
            Wiedza wiedza = new Wiedza();
            wiedza.IdI = idI;
            wiedza.IdR = idR;
            wiedza.Koncept = koncept;
            return wiedza;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdI
        {
            get
            {
                return _IdI;
            }
            set
            {
                if (_IdI != value)
                {
                    OnIdIChanging(value);
                    ReportPropertyChanging("IdI");
                    _IdI = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdI");
                    OnIdIChanged();
                }
            }
        }
        private global::System.Int32 _IdI;
        partial void OnIdIChanging(global::System.Int32 value);
        partial void OnIdIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdR
        {
            get
            {
                return _IdR;
            }
            set
            {
                if (_IdR != value)
                {
                    OnIdRChanging(value);
                    ReportPropertyChanging("IdR");
                    _IdR = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdR");
                    OnIdRChanged();
                }
            }
        }
        private global::System.Int32 _IdR;
        partial void OnIdRChanging(global::System.Int32 value);
        partial void OnIdRChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Koncept
        {
            get
            {
                return _Koncept;
            }
            set
            {
                if (_Koncept != value)
                {
                    OnKonceptChanging(value);
                    ReportPropertyChanging("Koncept");
                    _Koncept = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Koncept");
                    OnKonceptChanged();
                }
            }
        }
        private global::System.String _Koncept;
        partial void OnKonceptChanging(global::System.String value);
        partial void OnKonceptChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NpoziomDBModel", "FK_Wiedza_Instrumenty", "Instrumenty")]
        public Instrumenty Instrumenty
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Instrumenty>("NpoziomDBModel.FK_Wiedza_Instrumenty", "Instrumenty").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Instrumenty>("NpoziomDBModel.FK_Wiedza_Instrumenty", "Instrumenty").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Instrumenty> InstrumentyReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Instrumenty>("NpoziomDBModel.FK_Wiedza_Instrumenty", "Instrumenty");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Instrumenty>("NpoziomDBModel.FK_Wiedza_Instrumenty", "Instrumenty", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NpoziomDBModel", "FK_Wiedza_Relacje", "Relacje")]
        public Relacje Relacje
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Relacje>("NpoziomDBModel.FK_Wiedza_Relacje", "Relacje").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Relacje>("NpoziomDBModel.FK_Wiedza_Relacje", "Relacje").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Relacje> RelacjeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Relacje>("NpoziomDBModel.FK_Wiedza_Relacje", "Relacje");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Relacje>("NpoziomDBModel.FK_Wiedza_Relacje", "Relacje", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
